version: '3'

services:
  livekit:
    image: livekit/livekit-server:vfix-node-ip-SNAPSHOT
    restart: always
    ports:
      - '7880:7880'
      - '7881:7881'
      - '7882:7882/udp'
    expose:
      - 7880
      - 7881
      - '7882/udp'
      - '50000-60000/udp'
    volumes:
      - './livekit.yaml:/livekit.yaml'
    command: "--config /livekit.yaml --dev --node-ip 127.0.0.1"
  frontend:
    build:
      context: ./packages/frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend/src:/app/src
    environment:
      - LC_BACKEND_PATH=http://backend:8082
      - LC_BACKEND_SOCKET_PATH=http://backend:8083
      - LC_CONTAINER=true
  backend:
    build:
      context: ./packages/backend
    depends_on:
      - livekit
    ports:
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./packages/backend/src:/app/src
    env_file:
      - .env
    environment:
      - PORT=8082
      - SOCKET_PORT=8083
